In [1]:
!nvidia-smi

Thu Apr 24 17:35:00 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.35.03              Driver Version: 560.35.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8             10W /   70W |       1MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
from kaggle_secrets import UserSecretsClient
user_secrets = UserSecretsClient()
ASR_CHECKPOINT_LINK = user_secrets.get_secret("ASR_CHECKPOINT_FOLDER")

In [3]:
!rm -rf /kaggle/working/llm-speech-summarization

In [4]:
!git clone https://github.com/karimfathy054/llm-speech-summarization.git

Cloning into 'llm-speech-summarization'...
remote: Enumerating objects: 387, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 387 (delta 62), reused 45 (delta 29), pack-reused 294 (from 1)
Receiving objects: 100% (387/387), 164.14 KiB | 2.98 MiB/s, done.
Resolving deltas: 100% (189/189), done.


In [5]:
!pip install -r /kaggle/working/llm-speech-summarization/requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.7/524.7 kB 10.5 MB/s eta 0:00:0000:01
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of transformers to determine which version is compatible with other requirements. This could take a while.
INFO: pip is still looking at multiple versions of transformers to determine which version is compatible with other requirements. This could take a while.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.4/44.4 kB 2.5 MB/s eta 0:00:00
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings

In [6]:
import gdown
gdown.download_folder(ASR_CHECKPOINT_LINK)

Retrieving folder contents


Processing file 1wE7aghYl3Wy-BIn-QgY95z69LiDsUt6O speech_llm_audio_encoder.pt


Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From (original): https://drive.google.com/uc?id=1wE7aghYl3Wy-BIn-QgY95z69LiDsUt6O
From (redirected): https://drive.google.com/uc?id=1wE7aghYl3Wy-BIn-QgY95z69LiDsUt6O&confirm=t&uuid=0eff915f-b038-4796-bfc7-562af0dd3a24
To: /kaggle/working/Audio encoder checkpoint/speech_llm_audio_encoder.pt
100%|██████████| 1.27G/1.27G [00:07<00:00, 173MB/s] 
Download completed


['/kaggle/working/Audio encoder checkpoint/speech_llm_audio_encoder.pt']

In [7]:
# sanity check
# change the folder name if changed

!python /kaggle/working/llm-speech-summarization/inference.py -c /kaggle/working/llm-speech-summarization/config/config_full.yaml -g 0 -p "/kaggle/working/Audio encoder checkpoint/speech_llm_audio_encoder.pt" -a "/kaggle/input/audio-summarization-filtered-testset/audios/000571afe702684d90c1d222ce70b1e1375c1016.wav"

/kaggle/working/llm-speech-summarization/inference.py:20: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(audio_encoder_checkpoint, map_location="cpu")

In [8]:
%cd /kaggle/working/llm-speech-summarization
from inference import load_model , user_inference, LLMSpeechTextInference
llm_model = load_model("/kaggle/working/llm-speech-summarization/config/config_full.yaml",0,
               "/kaggle/working/Audio encoder checkpoint/speech_llm_audio_encoder.pt")

/kaggle/working/llm-speech-summarization


/kaggle/working/llm-speech-summarization/inference.py:20: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(audio_encoder_checkpoint, map_location="cpu")

Loaded audio encoder.



tokenizer_config.json:   0%|          | 0.00/1.26k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/749k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/411 [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


config.json:   0%|          | 0.00/674 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/6.04G [00:00<?, ?B/s]

Loaded LLM.

done


In [9]:
sample_audio = "/kaggle/input/audio-summarization-filtered-testset/audios/000571afe702684d90c1d222ce70b1e1375c1016.wav"
text_prompt = "summarize in bullet points"
response1 = user_inference(llm_model,sample_audio,user_prompt="text_prompt")
# torch.cuda.empty_cache()

combined_embeds:
tensor([[[ 1.2634e-02,  2.6855e-02, -1.0559e-02,  ...,  4.5166e-03,
           1.3245e-02, -2.0386e-02],
         [ 1.0254e-02,  1.3477e-01, -2.0020e-02,  ...,  1.0559e-02,
           3.4180e-02,  2.5024e-02],
         [-8.6060e-03,  1.4587e-02, -9.8267e-03,  ..., -3.7354e-02,
           1.2894e-03,  3.8086e-02],
         ...,
         [ 2.1242e+00, -2.4979e-01,  1.2839e+00,  ...,  1.0408e+00,
          -2.0490e-01,  3.5563e-02],
         [ 1.8539e+00, -9.8526e-03,  1.0844e+00,  ...,  1.4585e+00,
          -1.7900e-01,  4.5060e-01],
         [ 8.8512e-01,  2.0134e-01,  4.5713e-01,  ...,  7.0709e-01,
          -1.6380e-01,  3.1541e-01]]], device='cuda:1')
combined_embeds shape:
torch.Size([1, 1092, 3072])
prompt_emb_sequence:
tensor([[[ 0.0547, -0.0388, -0.0757,  ..., -0.0005,  0.0023,  0.0005],
         [ 0.0219, -0.0352,  0.0055,  ..., -0.0233, -0.0206,  0.0064],
         [-0.0078, -0.0425, -0.0043,  ...,  0.0247,  0.0167,  0.0415],
         ...,
         [-0.0205,  0

In [10]:
only_text_input = """
summarize in 5 sentences

The shape memory effect (SME) occurs because a temperature-induced phase transformation reverses deformation, as shown in the previous hysteresis curve. Typically the martensitic phase is monoclinic or orthorhombic (B19' or B19). Since these crystal structures do not have enough slip systems for easy dislocation motion, they deform by twinning—or rather, detwinning.

Martensite is thermodynamically favored at lower temperatures, while austenite (B2 cubic) is thermodynamically favored at higher temperatures. Since these structures have different lattice sizes and symmetry, cooling austenite into martensite introduces internal strain energy in the martensitic phase. To reduce this energy, the martensitic phase forms many twins—this is called "self-accommodating twinning" and is the twinning version of geometrically necessary dislocations. Since the shape memory alloy will be manufactured from a higher temperature and is usually engineered so that the martensitic phase is dominant at operating temperature to take advantage of the shape memory effect, SMAs "start" highly twinned.

When the martensite is loaded, these self-accommodating twins provide an easy path for deformation. Applied stresses will detwin the martensite, but all of the atoms stay in the same position relative to the nearby atoms—no atomic bonds are broken or reformed (as they would be by dislocation motion). Thus, when the temperature is raised and austenite becomes thermodynamically favored, all of the atoms rearrange to the B2 structure which happens to be the same macroscopic shape as the B19' pre-deformation shape. This phase transformation happens extremely quickly and gives SMAs their distinctive "snap."

Repeated use of the shape-memory effect may lead to a shift of the characteristic transformation temperatures (this effect is known as functional fatigue, as it is closely related with a change of microstructural and functional properties of the material). The maximum temperature at which SMAs can no longer be stress induced is called Md, where the SMAs are permanently deformed.
"""
response = llm_model.generate_text_response(only_text_input)
print(response)
# torch.cuda.empty_cache()


In summary, the shape memory effect is a unique property of certain metals and alloys that allows them to return to their original shape after being deformed, and this property is exploited in various applications such as self-healing materials, actuators, and sensors. The shape memory effect is a result of the martensitic phase forming self-accommodating twins, which provide an easy path for deformation when the material is loaded. When the temperature is raised and austenite becomes thermodynamically favored, all of the atoms rearrange to the B2 structure, which happens to be the same macroscopic shape as the B19' pre-deformation shape. This phase transformation happens extremely quickly and gives SMAs their distinctive "snap."


# ****Starting The Server Fast API****

In [11]:
!pip install fastapi uvicorn nest-asyncio pyngrok --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 3.9 MB/s eta 0:00:00


In [12]:
!pip install python-multipart
!pip install fastapi uvicorn pyngrok python-multipart nest_asyncio

In [13]:
from fastapi import FastAPI, File, UploadFile, Query,  Request 
from pydantic import BaseModel
import base64
from typing import Any
from fastapi.middleware.cors import CORSMiddleware
import nest_asyncio
from pyngrok import ngrok
import shutil
import os
import io
import uvicorn
import threading
res = "a"
app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["OPTIONS", "POST"],  # Explicitly list methods
    allow_headers=["*"],
)
class AudioRequest(BaseModel):
    filename: str
    content_type: str
    audio_data: str

UPLOAD_DIR = "uploads"
os.makedirs(UPLOAD_DIR, exist_ok=True)
@app.post("/upload")
async def upload_audio(audio_req: AudioRequest):
    audio_bytes = base64.b64decode(audio_req.audio_data)
    file_path = os.path.join(UPLOAD_DIR, "newAudio.wav")
    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(io.BytesIO(audio_bytes), buffer)
    result = user_inference(llm_model,file_path,user_prompt="text_prompt")
    print(result)
    return {"response": result}
@app.options("/model")
async def options_model():
    return {"message": "OK"}

@app.post("/model")
async def post_model(request: Request):
    data = await request.json()
    result = llm_model.generate_text_response(data.get('prompt'))
    print(result)
    return {"response": result}
# @app.options("/model")
# async def options_model():
#     return {"message": "Audio uploaded successfully"}

In [14]:
!ngrok config add-authtoken 2uMIRA3ZadTWnAb0gDkOnhX4Soz_7PwZiNj6n5DwWMujFdLsm
!pip install python-multipart


Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml                                


In [15]:
import nest_asyncio
import uvicorn
from threading import Thread
from fastapi import FastAPI
from pyngrok import ngrok


# Allow FastAPI to run inside Jupyter
nest_asyncio.apply()

public_url = ngrok.connect(8081)
print(f"Public URL: {public_url}")

# Run FastAPI app in a background thread
def run():
    uvicorn.run(app, host="0.0.0.0", port=8081)

thread = threading.Thread(target=run)
thread.start()

Public URL: NgrokTunnel: "https://58d8-34-55-218-130.ngrok-free.app" -> "http://localhost:8081"


In [16]:
import subprocess

subprocess.run("pkill -f uvicorn", shell=True)  # Linux/macOS
print(" Killed all Uvicorn processes")

 Killed all Uvicorn processes


INFO:     Started server process [31]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8081 (Press CTRL+C to quit)


INFO:     156.192.134.135:0 - "OPTIONS /upload HTTP/1.1" 200 OK
combined_embeds:
tensor([[[ 1.2634e-02,  2.6855e-02, -1.0559e-02,  ...,  4.5166e-03,
           1.3245e-02, -2.0386e-02],
         [ 1.0254e-02,  1.3477e-01, -2.0020e-02,  ...,  1.0559e-02,
           3.4180e-02,  2.5024e-02],
         [-8.6060e-03,  1.4587e-02, -9.8267e-03,  ..., -3.7354e-02,
           1.2894e-03,  3.8086e-02],
         ...,
         [ 1.9016e+00, -1.0122e-01,  1.2884e+00,  ...,  1.5275e+00,
          -1.2040e-01,  3.7825e-01],
         [ 1.1603e+00,  1.5421e-01,  6.5329e-01,  ...,  1.0374e+00,
          -1.2885e-01,  4.1804e-01],
         [ 3.5571e-01,  1.2862e-01,  1.6443e-01,  ...,  2.2094e-01,
          -9.3430e-02,  2.0325e-01]]], device='cuda:1')
combined_embeds shape:
torch.Size([1, 830, 3072])
prompt_emb_sequence:
tensor([[[ 0.0547, -0.0388, -0.0757,  ..., -0.0005,  0.0023,  0.0005],
         [ 0.0219, -0.0352,  0.0055,  ..., -0.0233, -0.0206,  0.0064],
         [-0.0078, -0.0425, -0.0043,  ..., 